language: php

php:
  - 5.6
  - hhvm

env:
  - RestApiResponseTest

before_script:
  - composer self-update
  - composer install

script: phpunit --coverage-text

notifications:
  email:
    - philipp.marien@gmail.com